package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"text/template"
)

type goField struct {
	Name string
	Type string
	Tag  string
}

type goStruct struct {
	Name   string
	Table  string
	Fields []goField
}

type modelFile struct {
	Package string
	Imports []string
	Structs []goStruct
}

func buildModelFile(cat *Catalog, pkg string) modelFile {
	mf := modelFile{Package: pkg}
	importSet := map[string]struct{}{}
	for _, t := range cat.Tables {
		s := goStruct{Name: structName(t.Name), Table: t.Name}
		for _, col := range t.Columns {
			gt := goTypeFor(col)
			if gt.Import != "" {
				importSet[gt.Import] = struct{}{}
			}
			s.Fields = append(s.Fields, goField{
				Name: goName(col.Name),
				Type: gt.Name,
				Tag:  fmt.Sprintf("`json:%q db:%q`", col.Name, col.Name),
			})
		}
		mf.Structs = append(mf.Structs, s)
	}
	for imp := range importSet {
		mf.Imports = append(mf.Imports, imp)
	}
	sort.Strings(mf.Imports)
	return mf
}

var modelsTmpl = template.Must(template.New("models").Parse(`// Code generated by sequa. DO NOT EDIT.

package {{.Package}}
{{if .Imports}}
import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)
{{end}}
{{- range .Structs}}
// {{.Name}} maps a row of the "{{.Table}}" table.
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} {{.Tag}}
{{- end}}
}
{{end}}`))

// RenderModels generates the models file (one struct per table) for a catalog,
// formatted with go/format (which also guarantees the output is valid Go).
func RenderModels(cat *Catalog, pkg string) ([]byte, error) {
	var buf bytes.Buffer
	if err := modelsTmpl.Execute(&buf, buildModelFile(cat, pkg)); err != nil {
		return nil, fmt.Errorf("render models: %w", err)
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format models: %w\n--- raw ---\n%s", err, buf.String())
	}
	return out, nil
}
