package codegen

import (
	"sort"
	"text/template"
)

type queryMethod struct {
	Name         string
	ConstName    string
	SQL          string
	IsExec       bool // :exec — returns error only
	IsExecRows   bool // :execrows — returns (int64, error)
	IsExecResult bool // :execresult — returns (sql.Result, error)
	IsOne        bool
	IsMany       bool
	Args         []goField // param args (Name + Type)
	ArgNames     []string
	RowType      string
	ScanList     []string
}

type queriesFile struct {
	Package    string
	Imports    []string
	RowStructs []goStruct
	Methods    []queryMethod
}

// RenderQueries generates the queries file (a Querier with typed methods) for
// the analyzed queries. Output is go/format-clean (and thus valid Go syntax).
func RenderQueries(cat *Catalog, queries []Query, pkg string) ([]byte, error) {
	qf := queriesFile{Package: pkg}
	importSet := map[string]struct{}{"context": {}, "database/sql": {}}

	for _, q := range queries {
		m, rowStruct := buildMethod(q, importSet)
		if rowStruct != nil {
			qf.RowStructs = append(qf.RowStructs, *rowStruct)
		}
		qf.Methods = append(qf.Methods, m)
	}
	for imp := range importSet {
		qf.Imports = append(qf.Imports, imp)
	}
	sort.Strings(qf.Imports)

	return renderFormatted(queriesTmpl, qf, "queries")
}

// buildMethod builds one query method and, for non-`*` result sets, the row
// struct it scans into (nil otherwise). Type imports are recorded in importSet.
func buildMethod(q Query, importSet map[string]struct{}) (queryMethod, *goStruct) {
	m := queryMethod{
		Name:         q.Name,
		ConstName:    lowerFirst(q.Name),
		SQL:          q.SQL,
		IsExec:       q.Cmd == CmdExec,
		IsExecRows:   q.Cmd == CmdExecRows,
		IsExecResult: q.Cmd == CmdExecResult,
		IsOne:        q.Cmd == CmdOne,
		IsMany:       q.Cmd == CmdMany,
	}
	for _, p := range q.Params {
		if p.GoType.Import != "" {
			importSet[p.GoType.Import] = struct{}{}
		}
		m.Args = append(m.Args, goField{Name: p.Name, Type: p.GoType.Name})
		m.ArgNames = append(m.ArgNames, p.Name)
	}
	if isExecFamily(q.Cmd) {
		return m, nil
	}
	var rowStruct *goStruct
	if q.Star {
		m.RowType = structName(q.Table)
	} else {
		m.RowType = q.Name + "Row"
		built := buildGoStruct(m.RowType, q.Table, q.Columns, importSet)
		rowStruct = &built
	}
	for _, col := range q.Columns {
		m.ScanList = append(m.ScanList, "&i."+goName(col.Name))
	}
	return m, rowStruct
}

var queriesTmpl = template.Must(template.New("queries").Parse(`// Code generated by sequa. DO NOT EDIT.

package {{.Package}}

import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// DBTX is the subset of *sql.DB / *sql.Tx the generated queries need.
type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

// New returns a Queries that runs against db.
func New(db DBTX) *Queries { return &Queries{db: db} }

// Queries holds the generated, type-safe query methods.
type Queries struct {
	db DBTX
}
{{range .RowStructs}}
// {{.Name}} is the result row of a generated query.
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} {{.Tag}}
{{- end}}
}
{{end}}
{{- range .Methods}}
const {{.ConstName}} = ` + "`{{.SQL}}`" + `

{{if .IsExec -}}
func (q *Queries) {{.Name}}(ctx context.Context{{range .Args}}, {{.Name}} {{.Type}}{{end}}) error {
	_, err := q.db.ExecContext(ctx, {{.ConstName}}{{range .ArgNames}}, {{.}}{{end}})
	return err
}
{{else if .IsExecRows -}}
func (q *Queries) {{.Name}}(ctx context.Context{{range .Args}}, {{.Name}} {{.Type}}{{end}}) (int64, error) {
	result, err := q.db.ExecContext(ctx, {{.ConstName}}{{range .ArgNames}}, {{.}}{{end}})
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
{{else if .IsExecResult -}}
func (q *Queries) {{.Name}}(ctx context.Context{{range .Args}}, {{.Name}} {{.Type}}{{end}}) (sql.Result, error) {
	return q.db.ExecContext(ctx, {{.ConstName}}{{range .ArgNames}}, {{.}}{{end}})
}
{{else if .IsOne -}}
func (q *Queries) {{.Name}}(ctx context.Context{{range .Args}}, {{.Name}} {{.Type}}{{end}}) ({{.RowType}}, error) {
	row := q.db.QueryRowContext(ctx, {{.ConstName}}{{range .ArgNames}}, {{.}}{{end}})
	var i {{.RowType}}
	err := row.Scan({{range $idx, $s := .ScanList}}{{if $idx}}, {{end}}{{$s}}{{end}})
	return i, err
}
{{else -}}
func (q *Queries) {{.Name}}(ctx context.Context{{range .Args}}, {{.Name}} {{.Type}}{{end}}) ([]{{.RowType}}, error) {
	rows, err := q.db.QueryContext(ctx, {{.ConstName}}{{range .ArgNames}}, {{.}}{{end}})
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	var items []{{.RowType}}
	for rows.Next() {
		var i {{.RowType}}
		if err := rows.Scan({{range $idx, $s := .ScanList}}{{if $idx}}, {{end}}{{$s}}{{end}}); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
{{end}}
{{- end}}`))
