package codegen

import (
	"sort"
	"text/template"
)

type queryMethod struct {
	Name      string
	ConstName string
	SQL       string
	IsExec    bool
	IsOne     bool
	IsMany    bool
	Args      []goField // param args (Name + Type)
	ArgNames  []string
	RowType   string
	ScanList  []string
}

type queriesFile struct {
	Package    string
	Imports    []string
	RowStructs []goStruct
	Methods    []queryMethod
}

// RenderQueries generates the queries file (a Querier with typed methods) for
// the analyzed queries. Output is go/format-clean (and thus valid Go syntax).
func RenderQueries(cat *Catalog, queries []Query, pkg string) ([]byte, error) {
	qf := queriesFile{Package: pkg}
	importSet := map[string]struct{}{"context": {}, "database/sql": {}}

	for _, q := range queries {
		m := queryMethod{
			Name:      q.Name,
			ConstName: lowerFirst(q.Name),
			SQL:       q.SQL,
			IsExec:    q.Cmd == CmdExec,
			IsOne:     q.Cmd == CmdOne,
			IsMany:    q.Cmd == CmdMany,
		}
		for _, p := range q.Params {
			if p.GoType.Import != "" {
				importSet[p.GoType.Import] = struct{}{}
			}
			m.Args = append(m.Args, goField{Name: p.Name, Type: p.GoType.Name})
			m.ArgNames = append(m.ArgNames, p.Name)
		}
		if q.Cmd != CmdExec {
			if q.Star {
				m.RowType = structName(q.Table)
			} else {
				m.RowType = q.Name + "Row"
				qf.RowStructs = append(qf.RowStructs, buildGoStruct(m.RowType, q.Table, q.Columns, importSet))
			}
			for _, col := range q.Columns {
				m.ScanList = append(m.ScanList, "&i."+goName(col.Name))
			}
		}
		qf.Methods = append(qf.Methods, m)
	}
	for imp := range importSet {
		qf.Imports = append(qf.Imports, imp)
	}
	sort.Strings(qf.Imports)

	return renderFormatted(queriesTmpl, qf, "queries")
}

var queriesTmpl = template.Must(template.New("queries").Parse(`// Code generated by sequa. DO NOT EDIT.

package {{.Package}}

import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)

// DBTX is the subset of *sql.DB / *sql.Tx the generated queries need.
type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

// New returns a Queries that runs against db.
func New(db DBTX) *Queries { return &Queries{db: db} }

// Queries holds the generated, type-safe query methods.
type Queries struct {
	db DBTX
}
{{range .RowStructs}}
// {{.Name}} is the result row of a generated query.
type {{.Name}} struct {
{{- range .Fields}}
	{{.Name}} {{.Type}} {{.Tag}}
{{- end}}
}
{{end}}
{{- range .Methods}}
const {{.ConstName}} = ` + "`{{.SQL}}`" + `

{{if .IsExec -}}
func (q *Queries) {{.Name}}(ctx context.Context{{range .Args}}, {{.Name}} {{.Type}}{{end}}) error {
	_, err := q.db.ExecContext(ctx, {{.ConstName}}{{range .ArgNames}}, {{.}}{{end}})
	return err
}
{{else if .IsOne -}}
func (q *Queries) {{.Name}}(ctx context.Context{{range .Args}}, {{.Name}} {{.Type}}{{end}}) ({{.RowType}}, error) {
	row := q.db.QueryRowContext(ctx, {{.ConstName}}{{range .ArgNames}}, {{.}}{{end}})
	var i {{.RowType}}
	err := row.Scan({{range $idx, $s := .ScanList}}{{if $idx}}, {{end}}{{$s}}{{end}})
	return i, err
}
{{else -}}
func (q *Queries) {{.Name}}(ctx context.Context{{range .Args}}, {{.Name}} {{.Type}}{{end}}) ([]{{.RowType}}, error) {
	rows, err := q.db.QueryContext(ctx, {{.ConstName}}{{range .ArgNames}}, {{.}}{{end}})
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()
	var items []{{.RowType}}
	for rows.Next() {
		var i {{.RowType}}
		if err := rows.Scan({{range $idx, $s := .ScanList}}{{if $idx}}, {{end}}{{$s}}{{end}}); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
{{end}}
{{- end}}`))
